version: "3.9"
services:
  database:
    container_name: strapi_database
    image: postgres:${DATABASE_VERSION:-15.4}
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-12345}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432/tcp"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tangem.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
  pgadmin:

networks:
  postgres:
    driver: bridge
